sudo: required
services:
  - docker

before_script:
  - docker build -f Dockerfile -t frlnbrg/graph graph
  - docker build -f Dockerfile -t 'frlnbrg/isunique arrays_and_strings\1.1'
script:
  - docker run frlnbrg/graph

  - docker run frlnbrg/isunique